Clearer tabs in view
Canop/Chrall pull request #84
Opened 2020-05-18 19:37 UTC by Falydoor

2020-05-19 07:08 UTC, fref reviewed
Je préférerais que tu mettes les dimensions en unités relatives (rem) plutôt que pixels

2020-05-20 07:57 UTC, fref requested changes
euh, non.
width est tjs en pixel
si tu veux utiliser rem, tu dois mettre ça au niveau du style  (style="width: 5rem")
et attention que 1 rem != 1 pixel
1 rem est relatif à la taille de fonte, donc potentiellement bcp bcp plus grand

2020-05-20 07:58 UTC, fref commented
75rem via style, ça donne ça:
![image](https://user-images.githubusercontent.com/130824/82420755-7523e700-9a80-11ea-89f1-98ebe5829bbe.png)

2020-05-20 14:20 UTC, Falydoor commented
Maintenant je comprends pourquoi je ne voyais pas de changement haha.

2020-05-20 14:45 UTC, fref approved these changes

2020-06-05 06:45 UTC, merged